version: "3.9"

services:
  db:
    image: postgres:14.4-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=votebot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-u", "postgres"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 10s
  test-vote-bot:
    build:
      target: tests
    environment:
      - SECRET_KEY=very_secret_testing_key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/votebot
    depends_on:
      db:
        condition: service_healthy
