version: "3.9"

services:
  db:
    image: postgres:14.4-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=votebot
    volumes:
      - database:/var/lib/postgresql/data
  vote-bot:
    build:
      target: production
    environment:
      - SECRET_KEY
      - DATABASE_URL
      - SIGNING_SECRET
      - SLACK_BOT_TOKEN
      - ENABLE_SCHEDULER
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./static:/var/www/static
    ports:
      - "8080:80"
    depends_on:
      - vote-bot

volumes:
  database:
