version: "3.9"

services:
  db:
    container_name: votebot-database
    image: postgres:14.4-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=votebot
    volumes:
      - votebot-database:/var/lib/postgresql/data
    networks:
      - votebot-network
  app:
    container_name: votebot-app
    image: votebot-app:${COMMIT_ID:-latest}
    build:
      target: production
    depends_on:
      - db
    networks:
      - votebot-network
  nginx:
    container_name: votebot-nginx
    image: votebot-nginx:${COMMIT_ID:-latest}
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./static:/var/www/static
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - votebot-network

volumes:
  votebot-database:
networks:
  votebot-network:
