version: "3.9"

services:
  db:
    container_name: votebot-database
    image: postgres:14.4-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=votebot
    volumes:
      - votebot-database:/var/lib/postgresql/data
  app:
    container_name: votebot-app
    image: votebot-app:${COMMIT_ID:-dev}
    build:
      target: production
    environment:
      - SECRET_KEY
      - DATABASE_URL
      - SIGNING_SECRET
      - SLACK_BOT_TOKEN
      - ENABLE_SCHEDULER
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    container_name: votebot-nginx
    image: votebot-nginx:${COMMIT_ID:-dev}
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./static:/var/www/static
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  votebot-database:
