version: "3.9"

services:
  db:
    container_name: votebot-database
    image: postgres:14.4-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=votebot
    volumes:
      - votebot-database:/var/lib/postgresql/data
    networks:
      - votebot-network
  app:
    container_name: votebot-app
    image: votebot-app:${COMMIT_ID:-latest}
    build:
      target: production
    environment:
      - SECRET_KEY=ABDSREARS839281630192
      - DATABASE_URL=postgres://postgres:postgres@db:5432/votebot
      - SIGNING_SECRET=0e78f66914db328b9ac4c2c2ea70b170
      - SLACK_BOT_TOKEN=xoxb-3421058008353-3933334983280-EKIbwAC5rX3aOoWAUpK7Ollb
      - ENABLE_SCHEDULER=1
    depends_on:
      - db
    networks:
      - votebot-network
  nginx:
    container_name: votebot-nginx
    image: votebot-nginx:${COMMIT_ID:-latest}
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./static:/var/www/static
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - votebot-network

volumes:
  votebot-database:
networks:
  votebot-network:
