# Generated by Django 4.0.4 on 2022-06-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('phone', models.TextField()),
                ('skype', models.TextField()),
                ('real_name', models.TextField(unique=True)),
                ('real_name_normalized', models.TextField()),
                ('display_name', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('team', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_id', models.TextField(blank=True, null=True, unique=True)),
                ('team_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('color', models.TextField(blank=True, null=True)),
                ('real_name', models.TextField(blank=True, null=True)),
                ('tz', models.TextField(blank=True, null=True)),
                ('tz_label', models.TextField(blank=True, null=True)),
                ('tz_offset', models.TextField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_primary_owner', models.BooleanField(default=False)),
                ('is_restricted', models.BooleanField(default=False)),
                ('is_ultra_restricted', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_app_user', models.BooleanField(default=False)),
                ('updated', models.SmallIntegerField(default=0)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('who_can_share_contact_card', models.TextField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_profile', to='bot_app.slackprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VotingResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_team_up_to_win', models.IntegerField(default=0)),
                ('points_act_to_deliver', models.IntegerField(default=0)),
                ('points_disrupt_to_grow', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('voted_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='voted_user', to='bot_app.slackuser')),
                ('voting_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='voting_user_id', to='bot_app.slackuser')),
            ],
        ),
    ]
